### ISSUE TITLE
Feature request(s): Suspend accounts at Institute or at Project level

### ISSUE THREAD

**Issue by DanielTosello** [Karaage-Cluster/karaage#387]
I'd like to be able to disable a group of accounts by their Institute or Project affiliations and restore them when appropriate.

**Comment by brianmay** [comment]
You mean you want to disable (lock?) all accounts in an institute/project and enable (unlock?) all accounts in an institute/project?

What happens if an account was already locked beforehand? Should it be enabled with the other accounts too?

**Comment by DanielTosello** [comment]
It should stay locked... yeah i know this requires extra fields for this to be present somewhere, either in the institution or on the person. Not an urgent feature by any means, but would be convenient for removing access from a project group or institution temporarily.

**Comment by brianmay** [comment]
So it sounds like what we need is another state for persons, similar to locked (I assume same restrictions - users can't login and won't receive emails), but separate from locked. Any ideas what we can call this?

**Comment by DanielTosello** [comment]
I've just been talking this out here and i actually think we want something different.

I don't know how it works exactly in PBS, but Slurm requests are allowed/denied on the basis of 'Account', which, in our case, is normally mapped from LDAP groups, and normally contains both institutes and projects as comparable entities. I think what we're actually after here is the ability to suspend ldap groups at the Slurm level. 

It might not be appropriate to do this via karaage without adding a bunch of ldap properties and changing the slurm interface.

**Comment by brianmay** [comment]
Just trying to understand the requirements more here.

The Karaage database model (and I think there are web views also) allows:

* To remove a person from a project.
* To remove the persons account. As in their LDAP and slurm credentials will get deleted. This would deactivate their `Account`, their default project for the account, their LDAP and Slurm credentials, but could keep the Person, their Karaage login, their projects, their institutes, their groups..

Does either of these sound like what you were after?

Possibly one limitation with the 2nd solution, is once an account is deactivated, there is no action to reactivate it again. I think we would have to create a new account, however if my reading of this code is correct they continue using the same username as before, so that shouldn't be a big issue.

(yes, I know, this ticket is 2 years old...)

**Comment by DanielTosello** [comment]
Honestly I think we have functionality that does what i was aiming for
here: a user can't execute jobs when they don't have an active project
authority behind them.

The cli management scripts i've written since then do all the things we
needed this for, with the added bonus that we don't have to clean up db or
posix perms... while there was some push to remove the user from the system
entirely, the people pushing for that aren't really aware of how
permissions interact between the systems.

I'm happy to close this.

**Comment by brianmay** [comment]
OK, closing.
