### ISSUE TITLE
Feature Request: Signup completion email 

### ISSUE THREAD

**Issue by DanielTosello** [Karaage-Cluster/karaage#802]
We recently started on a user admin workflow review. Mostly our workflows work really well, but the admin team picked out one sticking point - when a user is directed to karaage to do the initial signup process (as opposed to, say, our webpage with directions on how to use the service) there's nothing at the end of that process to tell them what to do next.

As such, the appropriate fix seems to be to add another email that gets sent after the completion of the initial password reset... of course, this requires a little refactoring of existing stuff, and splits password resets into two categories. We probably also, as part of that, want to add some interface to allow admins to edit templates from the application frontend... also aware it may need this pushed to the db as the existing templates are part of the deployment. 

Wanted to run it by you before I started making changes.

**Comment by brianmay** [comment]
Just to clarify, why would you need to split password resets into two categories?

Being able to edit  templates from the front end seems like a good idea initially. My previous company proposed something similar, just as I was leaving. However there is the potential for hidden problems. As a result, this project was about to be canned at my previous company.

Having email templates in Karaage means that there is one source of truth. That will get used for all deploys including karaage-testing. It also makes it easier to get formatting correct and consistent between emails - which might seem easy but unfortunately is not easy. Particularly when you have conditionals in some of these emails, and also need to get white space correct for text emails. Having email templates in Karaage means it is much more feasible to generate both text and html emails (something we don't actually do right now...).

Having said that the approval process was designed to allow for changes such as this. I think you would need a new transition. Instead of having `StatePassword` go directly to `C` state, you would have it go via the new transition state that sends the required email.

https://github.com/Karaage-Cluster/karaage/blob/master/karaage/conf/defaults.py#L492

Does this make sense?

**Comment by DanielTosello** [comment]
Because, I was assuming, you'd have the case where you're setting a new
user and they need the first time email response, and the case where
they're just setting the password.

I'll have to read up on how the various states in the application process
work (i don't think i'd actually seen them until now), but that seems to
make sense generally at least.

**Comment by brianmay** [comment]
Distinguishing the two cases might be the tricky part. Problem being at this time, the account has been created, and you can't tell the difference.

The `StatePassword` does check if the account has a usable password or not. But just because password is not usable doesn't mean account is new.  But maybe this is sufficient for your requirements?

Have a look at #811. Does this meet you requirements? Template still needs to be completed.

**Comment by brianmay** [comment]
Another option would be to add a new field - maybe a boolean field - to the `ProjectApplication` table to record if this is an application for a new user or an existing user.

**Comment by DanielTosello** [comment]
An optional boolean with a default value was my initial idea... that would
have the least impact, right?

Looking at the templates though, I now feel like a
karaage.plugins.kgapplications.views.states.StateWaitingForPasswordReset
would probably be the right way to do it to make it work with existing
code... but again, i'm less familiar with the codebase than you are.

**Comment by brianmay** [comment]
I have implemented this in #811. Please have a look.

I think the ability to update the emails requires more thought. At even if an attacker somehow managed to break into the system, get root access in the Docker container, and change the templates, redeploying the image would get us back to a sane state. Plus we have an audit log of all changes made to this template in git. All this would change if the website has the ability to update templates. Attackers would be able to silently alter messages, without any audit trail. As in we don't even log outgoing emails.

Which is probably something we should be doing actually. Every outgoing email - including subject, body, and recipients should be saved and recorded. So we have an audit trail of all outgoing emails - in case something goes wrong. Or if a user complains that they never received an email (this was a common occurrence at my previous employer). But maybe outside the scope of what is required by this issue.

**Comment by DanielTosello** [comment]
That makes perfect sense. We're more likely to want to control these kinds of things via puppet or similar in future, rather than having some local interface anyway.

Good point about outgoing emails, I've always relied on karaage's host to handle that... As you say it's probably a separate issue. I have some upcoming requests and might be able to get some people to help us with them, so I'll consider submitting it as a feature request when we get to that. 

The implementation looks good to me.
